export enum Category {
  NATURALEZA = 'naturaleza',
  ABSTRACTO = 'abstracto',
  URBANO = 'urbano',
  PERSONAS = 'personas',
  ANIMALES = 'animales',
  FRASES = 'frases',
  BOTANICO = 'botanico',
  MAPAS = 'mapas',
  INFANTIL = 'infantil',
  FOTOGRAFIA = 'fotografia',
  GASTRONOMIA = 'gastronomia',
  MUSICA = 'musica',
  CINE = 'cine',
  SUPERHEROES = 'superheroes',
  DEPORTES = 'deportes',
  MARINO = 'marino',
  ESPACIO = 'espacio',
  ARQUITECTURA = 'arquitectura',
  MODA = 'moda',
  RELIGIOSO = 'religioso',
  MITOLOGIA = 'mitologia',
  GEOMETRICO = 'geometrico',
}
