export enum Style {
  MINIMALISTA = 'minimalista',
  ACUARELA = 'acuarela',
  LINE_ART = 'line_art',
  POP_ART = 'pop_art',
  VINTAGE = 'vintage',
  NORDICO = 'nordico',
  JAPONES = 'japones',
  GEOMETRICO = 'geometrico',
  REALISTA = 'realista',
  SURREALISTA = 'surrealista',
  EXPRESIONISTA = 'expresionista',
  IMPRESIONISTA = 'impresionista',
  COLLAGE = 'collage',
  DIGITAL = 'digital',
  ILUSTRACION = 'ilustracion',
  FOTOGRAFIA_ARTISTICA = 'fotografia_artistica',
  ART_DECO = 'art_deco',
  GRAFFITI = 'graffiti',
  PIXEL_ART = 'pixel_art',
  CLASICO = 'clasico',
}
